# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   admin.category:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Galeria }
